spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/entrega
    username: postgres
    password: shadowfiter
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
      temp:
        use_jdbc_metadata_defaults: false
server:
  port: 9001
  context-path: /entrega